import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Stitch design tokens
        "on-background": "#1a1c1c",
        "background": "#f9f9f9",
        "outline": "#7c775f",
        "primary-container": "#e0f2fe",
        "surface-container-low": "#f3f3f3",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "secondary-container": "#e4e2e1",
        "on-secondary-fixed-variant": "#474747",
        "tertiary": "#006a69",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#0c4a6e",
        "error-container": "#ffdad6",
        "on-primary-container": "#0369a1",
        "secondary": "#5f5e5e",
        "on-primary": "#ffffff",
        "primary": "#0284c7",
        "on-surface": "#1a1c1c",
        "inverse-primary": "#38bdf8",
        "primary-fixed-dim": "#38bdf8",
        "on-primary-fixed-variant": "#075985",
        "surface-dim": "#dadada",
        "inverse-surface": "#2f3131",
        "surface": "#f9f9f9",
        "on-error": "#ffffff",
        "surface-variant": "#e2e2e2",
        "surface-tint": "#0284c7",
        "surface-container": "#eeeeee",
        "inverse-on-surface": "#f0f1f1",
        "error": "#ba1a1a",
        "on-secondary-container": "#656464",
        "on-secondary-fixed": "#1b1c1c",
        "primary-fixed": "#bae6fd",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#007171",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#4b4732",
        "outline-variant": "#cdc7aa",
        "surface-bright": "#f9f9f9",
        "secondary-fixed-dim": "#c8c6c6",
        "tertiary-fixed-dim": "#00dddc",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-headline)"],
        body: ["var(--font-sans)"],
        label: ["var(--font-sans)"],
        sans: ["var(--font-sans)"],
      },
      backgroundImage: {
        "hero-gradient": "linear-gradient(135deg, #0284c7 0%, #0369a1 100%)",
      },
    },
  },
  plugins: [],
};

export default config;
